/**
 * vc_webapi
 * Web API for the Virtual Classroom project
 *
 * The version of the OpenAPI document: v1
 * Contact: 237294@via.dk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RouterLink } from './routerLink';
import { RouterLinkParam } from './routerLinkParam';


export interface Notification { 
    id?: number;
    userId?: number;
    message?: string | null;
    notificationTimeUtc?: Date;
    dismissed?: boolean;
    routerLink?: RouterLink;
    routerLinkParameters?: Array<RouterLinkParam> | null;
}

