/**
 * vc_webapi
 * Web API for the Virtual Classroom project
 *
 * The version of the OpenAPI document: v1
 * Contact: 237294@via.dk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Course } from './course';


export interface ScheduledSession { 
    readonly id?: number;
    webuntisId: number;
    webuntisCourseId: number;
    courseId?: number;
    readonly course?: Course;
    roomId: number;
    startTime: Date;
    endTime: Date;
    webuntisTeacherIds?: Array<number> | null;
}

