/**
 * vc_webapi
 * Web API for the Virtual Classroom project
 *
 * The version of the OpenAPI document: v1
 * Contact: 237294@via.dk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Video } from './video';


export interface Session { 
    readonly id?: number;
    date?: Date;
    recordings?: Array<Video> | null;
    participants?: Array<User> | null;
}

