/**
 * vc_webapi
 * Web API for the Virtual Classroom project
 *
 * The version of the OpenAPI document: v1
 * Contact: 237294@via.dk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Comment } from './comment';


export interface User { 
    id?: number;
    userName?: string | null;
    fullName?: string | null;
    email?: string | null;
    isTeacher?: boolean;
    comments?: Array<Comment> | null;
}

