/**
 * vc_webapi
 * Web API for the Virtual Classroom project
 *
 * The version of the OpenAPI document: v1
 * Contact: 237294@via.dk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VideoProperties { 
    width?: number;
    height?: number;
    virtualFilePath?: string | null;
    fileSize?: number;
    mimeType: string | null;
    duration: number;
    containerExt: string | null;
}

