export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './comments.service';
import { CommentsService } from './comments.service';
export * from './courses.service';
import { CoursesService } from './courses.service';
export * from './enrollments.service';
import { EnrollmentsService } from './enrollments.service';
export * from './search.service';
import { SearchService } from './search.service';
export * from './videos.service';
import { VideosService } from './videos.service';
export * from './videostream.service';
import { VideostreamService } from './videostream.service';
export const APIS = [AuthenticationService, CommentsService, CoursesService, EnrollmentsService, SearchService, VideosService, VideostreamService];
