/**
 * vc_webapi
 * Web API for the Virtual Classroom project
 *
 * The version of the OpenAPI document: v1
 * Contact: 237294@via.dk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { EnrollUserModel } from '../model/enrollUserModel';
import { Enrollment } from '../model/enrollment';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class EnrollmentsService {

    protected basePath = 'http://localhost:58180';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * @param limitEnrollments 
     * @param includeSessions 
     * @param includeSessionParticipants 
     * @param includeSessionRecordings 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiEnrollmentsMyEnrollmentsGet(limitEnrollments?: number, includeSessions?: boolean, includeSessionParticipants?: boolean, includeSessionRecordings?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Array<Enrollment>>;
    public apiEnrollmentsMyEnrollmentsGet(limitEnrollments?: number, includeSessions?: boolean, includeSessionParticipants?: boolean, includeSessionRecordings?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Enrollment>>>;
    public apiEnrollmentsMyEnrollmentsGet(limitEnrollments?: number, includeSessions?: boolean, includeSessionParticipants?: boolean, includeSessionRecordings?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Enrollment>>>;
    public apiEnrollmentsMyEnrollmentsGet(limitEnrollments?: number, includeSessions?: boolean, includeSessionParticipants?: boolean, includeSessionRecordings?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (limitEnrollments !== undefined && limitEnrollments !== null) {
            queryParameters = queryParameters.set('limitEnrollments', <any>limitEnrollments);
        }
        if (includeSessions !== undefined && includeSessions !== null) {
            queryParameters = queryParameters.set('includeSessions', <any>includeSessions);
        }
        if (includeSessionParticipants !== undefined && includeSessionParticipants !== null) {
            queryParameters = queryParameters.set('includeSessionParticipants', <any>includeSessionParticipants);
        }
        if (includeSessionRecordings !== undefined && includeSessionRecordings !== null) {
            queryParameters = queryParameters.set('includeSessionRecordings', <any>includeSessionRecordings);
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Array<Enrollment>>(`${this.configuration.basePath}/api/Enrollments/MyEnrollments`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param enrollUserModel 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiEnrollmentsPost(enrollUserModel?: EnrollUserModel, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiEnrollmentsPost(enrollUserModel?: EnrollUserModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiEnrollmentsPost(enrollUserModel?: EnrollUserModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiEnrollmentsPost(enrollUserModel?: EnrollUserModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.configuration.basePath}/api/Enrollments`,
            enrollUserModel,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
