/**
 * vc_webapi
 * Web API for the Virtual Classroom project
 *
 * The version of the OpenAPI document: v1
 * Contact: 237294@via.dk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { Room } from '../model/room';
import { RoomRecordingSchedule } from '../model/roomRecordingSchedule';
import { ScheduledSession } from '../model/scheduledSession';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class ScheduleService {

    protected basePath = 'http://localhost:58180';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }



    /**
     * @param room 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiScheduleAddRoomPost(room?: Room, observe?: 'body', reportProgress?: boolean): Observable<Room>;
    public apiScheduleAddRoomPost(room?: Room, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Room>>;
    public apiScheduleAddRoomPost(room?: Room, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Room>>;
    public apiScheduleAddRoomPost(room?: Room, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Room>(`${this.configuration.basePath}/api/Schedule/AddRoom`,
            room,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param roomName 
     * @param startUtc 
     * @param endUtc 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiScheduleForRoomRoomNameGet(roomName: string, startUtc?: Date, endUtc?: Date, observe?: 'body', reportProgress?: boolean): Observable<RoomRecordingSchedule>;
    public apiScheduleForRoomRoomNameGet(roomName: string, startUtc?: Date, endUtc?: Date, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<RoomRecordingSchedule>>;
    public apiScheduleForRoomRoomNameGet(roomName: string, startUtc?: Date, endUtc?: Date, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<RoomRecordingSchedule>>;
    public apiScheduleForRoomRoomNameGet(roomName: string, startUtc?: Date, endUtc?: Date, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (roomName === null || roomName === undefined) {
            throw new Error('Required parameter roomName was null or undefined when calling apiScheduleForRoomRoomNameGet.');
        }

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (startUtc !== undefined && startUtc !== null) {
            queryParameters = queryParameters.set('startUtc', <any>startUtc.toISOString());
        }
        if (endUtc !== undefined && endUtc !== null) {
            queryParameters = queryParameters.set('endUtc', <any>endUtc.toISOString());
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<RoomRecordingSchedule>(`${this.configuration.basePath}/api/Schedule/ForRoom/${encodeURIComponent(String(roomName))}`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param limit 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiScheduleGetRoomsGet(limit?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<Room>>;
    public apiScheduleGetRoomsGet(limit?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<Room>>>;
    public apiScheduleGetRoomsGet(limit?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<Room>>>;
    public apiScheduleGetRoomsGet(limit?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<Array<Room>>(`${this.configuration.basePath}/api/Schedule/GetRooms`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * @param scheduledSession 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiSchedulePost(scheduledSession?: Array<ScheduledSession>, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiSchedulePost(scheduledSession?: Array<ScheduledSession>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiSchedulePost(scheduledSession?: Array<ScheduledSession>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiSchedulePost(scheduledSession?: Array<ScheduledSession>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (bearer) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.configuration.basePath}/api/Schedule`,
            scheduledSession,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
